### PR TITLE
prepare update to async/await

### PR DESCRIPTION
**Pull request by hyyking**
prepare bump to async await and new tokio interface

### CODE REVIEW

**Comment by 1tgr** [comment]
@hyyking do you have the version numbers for the tokio dependencies used by 1tgr/rust-websocket-lite?

**Comment by hyyking** [comment]
[this one](https://github.com/1tgr/rust-websocket-lite/blob/master/Cargo.tomll) basically latest 0.1 (1.22.0)

**Comment by 1tgr** [comment]
Sorry, I mean: this PR bumps the versions of dependencies needed by 1tgr/rust-websocket-codec, which is only tokio-codec.

In 1tgr/rust-websocket there are more tokio dependencies which need version bumps. Do you have a set of version bumps that allow it to compile?

It seems it's not enough to use the latest `-alpha` version of all dependencies, since:
```
error: failed to select a version for `futures-core-preview`.
    ... required by package `tokio-tcp v0.2.0-alpha.1`
    ... which is depended on by `websocket-lite v0.2.4 (/Users/tim/Git.local/rust-websocket-lite)`
versions that meet the requirements `= 0.3.0-alpha.17` are: 0.3.0-alpha.17

all possible versions conflict with previously selected packages.

  previously selected package `futures-core-preview v0.3.0-alpha.19`
    ... which is depended on by `tokio-codec v0.2.0-alpha.6`
    ... which is depended on by `websocket-lite v0.2.4 (/Users/tim/Git.local/rust-websocket-lite)`

failed to select a version for `futures-core-preview` which could resolve this conflict
```

**Comment by 1tgr** [comment]
I don't think we're ready for this as the changes on websocket-lite are substantial. Better to wait for the tokio structure to stabilise.

For instance, tokio-rs/tokio#1675 moves the codec types into a new crate, which is not yet published on crates.io.

**Comment by 1tgr** [comment]
This is good, I'll follow with the changes on websocket-lite.

**Comment by hyyking** [comment]
Sorry for not responding, I considered this to be a first step towards async/await websocket crates older versions of the websocket-lite crate should use older versions of this codec crate

**Pull request merged**
